FROM ubuntu:20.04

ENV  POETRY_VIRTUALENVS_IN_PROJECT=true \
  POETRY_HOME="/home/poetry" \
  VENV_PATH="/home/ml_app .venv" \
  USER="ml_app"

ENV  PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

RUN useradd $USER

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y python3-dev python3-pip \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip \
  && pip3 install poetry==1.2.0a2 \
  && wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
  && tar -xvf ta-lib-0.4.0-src.tar.gz \
  && cd ta-lib/ \
  && ./configure --prefix=/usr \
  && make \
  && make install


WORKDIR /home/ml_app

COPY pyproject.toml poetry.lock ./
RUN poetry install --without dev

COPY ml_app/app app
COPY ml_app/ml_app.py ml_app/config.py ml_app/entrypoint.sh .env ./
RUN chmod +x entrypoint.sh

ENV FLASK_APP ml_app.py

RUN chown -R ml_app:ml_app /home/ml_app
USER $USER

EXPOSE 5000

ENTRYPOINT ["sh", "./entrypoint.sh"]
