name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${% raw %}{{secrets.SONAR_TOKEN}}{% endraw %}
          SONAR_HOST_URL: ${% raw %}{{secrets.SONAR_HOST_URL}}{% endraw %}
